name: Lint
on:
  push:
    branches:
      - develop
permissions:
  pull-requests: write
  contents: write
env:
  GH_TOKEN: ${{ github.token }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
  COMMIT_ID: ${{ github.sha }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create new branch
        run: |
          git checkout $BRANCH_NAME
          git checkout -b "$BRANCH_NAME-lint-$COMMIT_ID"
          git push -u origin "$BRANCH_NAME-lint-$COMMIT_ID"
          echo "Data" >> my_file.txt
          git add .
          git commit -m "new data"
          git push
          gh pr create --fill --base $BRANCH_NAME --head "$BRANCH_NAME-lint-$COMMIT_ID"
