name: Lint
on:
  push:
    branches:
      - develop
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr create --title Lint --template lint-pr-template.md